title: Dryade's Corner
description:
  This is a space for me to write about whatever I want without people knowing who I am.
baseurl: ""
url: "https://dryadele.github.io"

theme: minima
plugins:
  - jekyll-feed
include:
  - _pages
  - _assets
